window.esdocSearchIndex = [
  [
    "unicast-definition/lib/interfaces/ipsp.js~ipsp",
    "class/lib/interfaces/ipsp.js~IPSP.html",
    "<span>IPSP</span> <span class=\"search-result-import-path\">unicast-definition/lib/interfaces/ipsp.js</span>",
    "class"
  ],
  [
    "unicast-definition/lib/messages/municast.js~municast",
    "class/lib/messages/municast.js~MUnicast.html",
    "<span>MUnicast</span> <span class=\"search-result-import-path\">unicast-definition/lib/messages/municast.js</span>",
    "class"
  ],
  [
    "unicast-definition~unicast",
    "class/lib/unicast.js~Unicast.html",
    "<span>Unicast</span> <span class=\"search-result-import-path\">unicast-definition</span>",
    "class"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/interfaces/ipsp.js",
    "file/lib/interfaces/ipsp.js.html",
    "lib/interfaces/ipsp.js",
    "file"
  ],
  [
    "lib/interfaces/ipsp.js~ipsp#_receive",
    "class/lib/interfaces/ipsp.js~IPSP.html#instance-method-_receive",
    "lib/interfaces/ipsp.js~IPSP#_receive",
    "method"
  ],
  [
    "lib/interfaces/ipsp.js~ipsp#send",
    "class/lib/interfaces/ipsp.js~IPSP.html#instance-method-send",
    "lib/interfaces/ipsp.js~IPSP#send",
    "method"
  ],
  [
    "lib/messages/municast.js",
    "file/lib/messages/municast.js.html",
    "lib/messages/municast.js",
    "file"
  ],
  [
    "lib/messages/municast.js~municast#args",
    "class/lib/messages/municast.js~MUnicast.html#instance-member-args",
    "lib/messages/municast.js~MUnicast#args",
    "member"
  ],
  [
    "lib/messages/municast.js~municast#constructor",
    "class/lib/messages/municast.js~MUnicast.html#instance-constructor-constructor",
    "lib/messages/municast.js~MUnicast#constructor",
    "method"
  ],
  [
    "lib/messages/municast.js~municast#event",
    "class/lib/messages/municast.js~MUnicast.html#instance-member-event",
    "lib/messages/municast.js~MUnicast#event",
    "member"
  ],
  [
    "lib/messages/municast.js~municast#pid",
    "class/lib/messages/municast.js~MUnicast.html#instance-member-pid",
    "lib/messages/municast.js~MUnicast#pid",
    "member"
  ],
  [
    "lib/messages/municast.js~municast#type",
    "class/lib/messages/municast.js~MUnicast.html#instance-member-type",
    "lib/messages/municast.js~MUnicast#type",
    "member"
  ],
  [
    "lib/unicast.js",
    "file/lib/unicast.js.html",
    "lib/unicast.js",
    "file"
  ],
  [
    "lib/unicast.js~unicast#_emit",
    "class/lib/unicast.js~Unicast.html#instance-member-_emit",
    "lib/unicast.js~Unicast#_emit",
    "member"
  ],
  [
    "lib/unicast.js~unicast#constructor",
    "class/lib/unicast.js~Unicast.html#instance-constructor-constructor",
    "lib/unicast.js~Unicast#constructor",
    "method"
  ],
  [
    "lib/unicast.js~unicast#destroy",
    "class/lib/unicast.js~Unicast.html#instance-method-destroy",
    "lib/unicast.js~Unicast#destroy",
    "method"
  ],
  [
    "lib/unicast.js~unicast#emit",
    "class/lib/unicast.js~Unicast.html#instance-member-emit",
    "lib/unicast.js~Unicast#emit",
    "member"
  ],
  [
    "lib/unicast.js~unicast#options",
    "class/lib/unicast.js~Unicast.html#instance-member-options",
    "lib/unicast.js~Unicast#options",
    "member"
  ],
  [
    "lib/unicast.js~unicast#psp",
    "class/lib/unicast.js~Unicast.html#instance-member-psp",
    "lib/unicast.js~Unicast#psp",
    "member"
  ]
]